from decimal import Decimal

APP_NAME = "FastBank"
API_VERSION = "v1"

ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
REFRESH_TOKEN_EXPIRE_DAYS = 7

MAX_LOAN_AMOUNT = Decimal("10000000.00")
MIN_LOAN_AMOUNT = Decimal("10000.00")

DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

RATE_LIMIT_WINDOW_SECONDS = 60
RATE_LIMIT_TIMES = 5
