"""added loan_type relation and decision fields

Revision ID: 0bb64a4cc196
Revises: d0227a30a14d
Create Date: 2026-02-14 11:27:47.121907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb64a4cc196'
down_revision: Union[str, Sequence[str], None] = 'd0227a30a14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('loan_type_id', sa.UUID(), nullable=False))
    op.add_column('loans', sa.Column('decided_by', sa.UUID(), nullable=True))
    op.add_column('loans', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('loans_approved_by_fkey'), 'loans', type_='foreignkey')
    op.create_foreign_key(None, 'loans', 'loan_types', ['loan_type_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'loans', 'users', ['decided_by'], ['id'], ondelete='SET NULL')
    op.drop_column('loans', 'approved_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.create_foreign_key(op.f('loans_approved_by_fkey'), 'loans', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.drop_column('loans', 'rejection_reason')
    op.drop_column('loans', 'decided_by')
    op.drop_column('loans', 'loan_type_id')
    # ### end Alembic commands ###
