"""add loan_repayment table

Revision ID: 3bdcd4a84a3d
Revises: c1e50cc5fdf8
Create Date: 2026-02-14 17:52:25.594812

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3bdcd4a84a3d"
down_revision: Union[str, Sequence[str], None] = "c1e50cc5fdf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loan_repayments",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("amount_paid", sa.BigInteger(), nullable=False),
        sa.Column("principal_component", sa.BigInteger(), nullable=False),
        sa.Column("interest_component", sa.BigInteger(), nullable=False),
        sa.Column(
            "payment_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCESS",
                "FAILED",
                name="repayment_status_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount_paid > 0", name="check_amount_paid_positive"),
        sa.CheckConstraint(
            "interest_component >= 0", name="check_interest_component_valid"
        ),
        sa.CheckConstraint(
            "principal_component + interest_component = amount_paid",
            name="check_payment_split_valid",
        ),
        sa.CheckConstraint(
            "principal_component >= 0", name="check_principal_component_valid"
        ),
        sa.ForeignKeyConstraint(["loan_id"], ["loans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_repayments_loan_id"), "loan_repayments", ["loan_id"], unique=False
    )
    op.create_index(
        op.f("ix_loan_repayments_status"), "loan_repayments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_loan_repayments_tenant_id"),
        "loan_repayments",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_loan_repayments_transaction_id"),
        "loan_repayments",
        ["transaction_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_loan_repayments_transaction_id"), table_name="loan_repayments"
    )
    op.drop_index(op.f("ix_loan_repayments_tenant_id"), table_name="loan_repayments")
    op.drop_index(op.f("ix_loan_repayments_status"), table_name="loan_repayments")
    op.drop_index(op.f("ix_loan_repayments_loan_id"), table_name="loan_repayments")
    op.drop_table("loan_repayments")
    # ### end Alembic commands ###
