"""add CLOSED and FORECLOSED loan statuses

Revision ID: 95f843c84ff7
Revises: 3bdcd4a84a3d
Create Date: 2026-02-14 19:23:51.987495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "95f843c84ff7"
down_revision: Union[str, Sequence[str], None] = "3bdcd4a84a3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We must commit the current transaction before altering the enum type
    op.execute("COMMIT")
    op.execute("ALTER TYPE loan_status_enum ADD VALUE 'CLOSED'")
    op.execute("ALTER TYPE loan_status_enum ADD VALUE 'FORECLOSED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing enum values is complex in Postgres, manual intervention required if needed
    pass
    # ### end Alembic commands ###
