"""change_balance_and_amount_to_bigint

Revision ID: 9ea8442a0afa
Revises: c4eb66be76bf
Create Date: 2026-02-12 13:07:12.892958

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9ea8442a0afa"
down_revision: Union[str, Sequence[str], None] = "c4eb66be76bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accounts",
        "balance",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.BigInteger(),
        type_=sa.NUMERIC(precision=15, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "accounts",
        "balance",
        existing_type=sa.BigInteger(),
        type_=sa.NUMERIC(precision=15, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
