"""Refactor account_type to foreign key

Revision ID: bd66b7c9fd4a
Revises: 43cb57202658
Create Date: 2026-02-14 22:21:48.543871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd66b7c9fd4a'
down_revision: Union[str, Sequence[str], None] = '43cb57202658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_type_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_tenant_user_type'), table_name='accounts')
    op.create_index('ix_accounts_tenant_user_type', 'accounts', ['tenant_id', 'user_id', 'account_type_id'], unique=True)
    op.create_index(op.f('ix_accounts_account_type_id'), 'accounts', ['account_type_id'], unique=False)
    op.create_foreign_key(None, 'accounts', 'account_types', ['account_type_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('accounts', 'account_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_type', postgresql.ENUM('SAVINGS', 'CURRENT', name='account_type_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_account_type_id'), table_name='accounts')
    op.drop_index('ix_accounts_tenant_user_type', table_name='accounts')
    op.create_index(op.f('ix_accounts_tenant_user_type'), 'accounts', ['tenant_id', 'user_id', 'account_type'], unique=True)
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.drop_column('accounts', 'account_type_id')
    # ### end Alembic commands ###
