"""added emi_amount and remaining_principal in loan table

Revision ID: c1e50cc5fdf8
Revises: 0bb64a4cc196
Create Date: 2026-02-14 14:43:08.776211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c1e50cc5fdf8"
down_revision: Union[str, Sequence[str], None] = "0bb64a4cc196"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "loans", sa.Column("remaining_principal", sa.BigInteger(), nullable=False)
    )
    op.add_column("loans", sa.Column("emi_amount", sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loans", "emi_amount")
    op.drop_column("loans", "remaining_principal")
    # ### end Alembic commands ###
