"""added account and interest rule tables

Revision ID: d0227a30a14d
Revises: cd0ad50e5fbe
Create Date: 2026-02-13 21:56:29.981851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0227a30a14d'
down_revision: Union[str, Sequence[str], None] = 'cd0ad50e5fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_types',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_types',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest_rules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.Enum('ACCOUNT', 'LOAN', name='rule_type_enum', create_constraint=True), nullable=False),
    sa.Column('account_type_id', sa.UUID(), nullable=True),
    sa.Column('loan_type_id', sa.UUID(), nullable=True),
    sa.Column('min_balance', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('max_balance', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_type_id'], ['loan_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interest_rules_account_type_id'), 'interest_rules', ['account_type_id'], unique=False)
    op.create_index(op.f('ix_interest_rules_loan_type_id'), 'interest_rules', ['loan_type_id'], unique=False)
    op.create_index(op.f('ix_interest_rules_rule_type'), 'interest_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_interest_rules_tenant_id'), 'interest_rules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interest_rules_tenant_id'), table_name='interest_rules')
    op.drop_index(op.f('ix_interest_rules_rule_type'), table_name='interest_rules')
    op.drop_index(op.f('ix_interest_rules_loan_type_id'), table_name='interest_rules')
    op.drop_index(op.f('ix_interest_rules_account_type_id'), table_name='interest_rules')
    op.drop_table('interest_rules')
    op.drop_table('loan_types')
    op.drop_table('account_types')
    # ### end Alembic commands ###
